// generated by ../sqlpp11/scripts/ddl2cpp ./timer.sql timer_db TimerDB
#ifndef TIMERDB_TIMER_DB_H
#define TIMERDB_TIMER_DB_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace TimerDB
{
  namespace Entries_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  }

  struct Entries: sqlpp::table_t<Entries,
               Entries_::Id>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "entries";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T entries;
        T& operator()() { return entries; }
        const T& operator()() const { return entries; }
      };
    };
  };
}
#endif
