[package]
name = "rust"
version = "0.1.0"
edition = "2018"

[lib]
name = "rust"
crate-type = ["staticlib"]

[dependencies]
chrono = "0.4.*"
diesel = { version = "1.4.*", features = ["sqlite"] }
libc = "*"
once_cell = "1.7.*"
#sysinfo = "0.3.16"


