[package]
name = "rust"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "*"
sysinfo = "0.3.16"
diesel = { version = "1.1.0", features = ["sqlite"] }

[lib]
name = "rust"
crate-type = ["staticlib"]
